### ISSUE TITLE
Use deserialization from byte stream instead of byte slice

### ISSUE THREAD

**Issue by ebirukov** [jkeys089/jserial#2]
@jkeys089 I really liked your implementation of the java serialization protocol, it is simple and convenient. But I need to use deserialization for a stream of bytes. The bytes of the serialized objects that I have to deserialize are part of the data in the stream. The stream itself contains data bytes before and after the bytes of the serialized object. Because Since this implementation uses a slice of bytes, I cannot extract the data bytes related to the deserialized object. As a solution, I need an io.Reader, or even better a bufio.Reader, so that I can use buffered stream features like unreadByte and Peek. 
The java serialization protocol does not contain end-of-byte markers for the serialized object in the stream. It is necessary to be able to complete the deserialization procedure and ignore the "unknown type" error of the serializedObjectParser.content method

**Comment by jkeys089** [comment]
@ebirukov If I understand correctly, you're asking for this project to support loading serialized Java objects via an `io.Reader`, right? I think that's a really good idea. I'll leave this issue open in case someone wants to contribute that feature.

**Comment by ebirukov** [comment]
> @ebirukov If I understand correctly, you're asking for this project to support loading serialized Java objects via an `io.Reader`, right?

Yes, I will try to modify your code to support streaming implementation
